import XCTest

extension DictionaryDecoderTests {
    static let __allTests = [
        ("testKeyedContainerAllKeys", testKeyedContainerAllKeys),
        ("testKeyedContainerContainsKeys", testKeyedContainerContainsKeys),
        ("testKeyedContainerDecodesBool", testKeyedContainerDecodesBool),
        ("testKeyedContainerDecodesDouble", testKeyedContainerDecodesDouble),
        ("testKeyedContainerDecodesFloat", testKeyedContainerDecodesFloat),
        ("testKeyedContainerDecodesInt16", testKeyedContainerDecodesInt16),
        ("testKeyedContainerDecodesInt32", testKeyedContainerDecodesInt32),
        ("testKeyedContainerDecodesInt64", testKeyedContainerDecodesInt64),
        ("testKeyedContainerDecodesInt8", testKeyedContainerDecodesInt8),
        ("testKeyedContainerDecodesInt", testKeyedContainerDecodesInt),
        ("testKeyedContainerDecodesNestedKeyed", testKeyedContainerDecodesNestedKeyed),
        ("testKeyedContainerDecodesNestedSingleType", testKeyedContainerDecodesNestedSingleType),
        ("testKeyedContainerDecodesNestedType", testKeyedContainerDecodesNestedType),
        ("testKeyedContainerDecodesNestedUnkeyed", testKeyedContainerDecodesNestedUnkeyed),
        ("testKeyedContainerDecodesNestedUnkeyedKeyed", testKeyedContainerDecodesNestedUnkeyedKeyed),
        ("testKeyedContainerDecodesNil", testKeyedContainerDecodesNil),
        ("testKeyedContainerDecodesString", testKeyedContainerDecodesString),
        ("testKeyedContainerDecodesUInt16", testKeyedContainerDecodesUInt16),
        ("testKeyedContainerDecodesUInt32", testKeyedContainerDecodesUInt32),
        ("testKeyedContainerDecodesUInt64", testKeyedContainerDecodesUInt64),
        ("testKeyedContainerDecodesUInt8", testKeyedContainerDecodesUInt8),
        ("testKeyedContainerDecodesUInt", testKeyedContainerDecodesUInt),
        ("testKeyedDecoderThrowsUnexpectedContainer", testKeyedDecoderThrowsUnexpectedContainer),
        ("testSimpleDecodeFromDictionaryFails", testSimpleDecodeFromDictionaryFails),
        ("testSimpleDecodeFromDictionarySucceeds", testSimpleDecodeFromDictionarySucceeds),
        ("testSingleContainerDecodesBool", testSingleContainerDecodesBool),
        ("testSingleContainerDecodesDecodable", testSingleContainerDecodesDecodable),
        ("testSingleContainerDecodesDouble", testSingleContainerDecodesDouble),
        ("testSingleContainerDecodesFloat", testSingleContainerDecodesFloat),
        ("testSingleContainerDecodesInt16", testSingleContainerDecodesInt16),
        ("testSingleContainerDecodesInt32", testSingleContainerDecodesInt32),
        ("testSingleContainerDecodesInt64", testSingleContainerDecodesInt64),
        ("testSingleContainerDecodesInt8", testSingleContainerDecodesInt8),
        ("testSingleContainerDecodesInt", testSingleContainerDecodesInt),
        ("testSingleContainerDecodesNil", testSingleContainerDecodesNil),
        ("testSingleContainerDecodesString", testSingleContainerDecodesString),
        ("testSingleContainerDecodesUInt16", testSingleContainerDecodesUInt16),
        ("testSingleContainerDecodesUInt32", testSingleContainerDecodesUInt32),
        ("testSingleContainerDecodesUInt64", testSingleContainerDecodesUInt64),
        ("testSingleContainerDecodesUInt8", testSingleContainerDecodesUInt8),
        ("testSingleContainerDecodesUInt", testSingleContainerDecodesUInt),
        ("testSuperEncoder", testSuperEncoder),
        ("testUnkeyedContainerDecodesBool", testUnkeyedContainerDecodesBool),
        ("testUnkeyedContainerDecodesDouble", testUnkeyedContainerDecodesDouble),
        ("testUnkeyedContainerDecodesFloat", testUnkeyedContainerDecodesFloat),
        ("testUnkeyedContainerDecodesInt16", testUnkeyedContainerDecodesInt16),
        ("testUnkeyedContainerDecodesInt32", testUnkeyedContainerDecodesInt32),
        ("testUnkeyedContainerDecodesInt64", testUnkeyedContainerDecodesInt64),
        ("testUnkeyedContainerDecodesInt8", testUnkeyedContainerDecodesInt8),
        ("testUnkeyedContainerDecodesInt", testUnkeyedContainerDecodesInt),
        ("testUnkeyedContainerDecodesNestedKeyed", testUnkeyedContainerDecodesNestedKeyed),
        ("testUnkeyedContainerDecodesNestedSingleType", testUnkeyedContainerDecodesNestedSingleType),
        ("testUnkeyedContainerDecodesNestedType", testUnkeyedContainerDecodesNestedType),
        ("testUnkeyedContainerDecodesNestedUnkeyed", testUnkeyedContainerDecodesNestedUnkeyed),
        ("testUnkeyedContainerDecodesNil", testUnkeyedContainerDecodesNil),
        ("testUnkeyedContainerDecodesString", testUnkeyedContainerDecodesString),
        ("testUnkeyedContainerDecodesUInt16", testUnkeyedContainerDecodesUInt16),
        ("testUnkeyedContainerDecodesUInt32", testUnkeyedContainerDecodesUInt32),
        ("testUnkeyedContainerDecodesUInt64", testUnkeyedContainerDecodesUInt64),
        ("testUnkeyedContainerDecodesUInt8", testUnkeyedContainerDecodesUInt8),
        ("testUnkeyedContainerDecodesUInt", testUnkeyedContainerDecodesUInt),
        ("testUnkeyedGetStorageIncrementsIndex", testUnkeyedGetStorageIncrementsIndex),
    ]
}

extension DictionaryEncoderTests {
    static let __allTests = [
        ("testEmptyStructIsEncoded", testEmptyStructIsEncoded),
        ("testEncode", testEncode),
        ("testEncodeSingleValueThrows", testEncodeSingleValueThrows),
        ("testIndexKeyCannotInitializeWithStringValue", testIndexKeyCannotInitializeWithStringValue),
        ("testKeyedContainerEncodesBool", testKeyedContainerEncodesBool),
        ("testKeyedContainerEncodesDouble", testKeyedContainerEncodesDouble),
        ("testKeyedContainerEncodesFloat", testKeyedContainerEncodesFloat),
        ("testKeyedContainerEncodesInt16", testKeyedContainerEncodesInt16),
        ("testKeyedContainerEncodesInt32", testKeyedContainerEncodesInt32),
        ("testKeyedContainerEncodesInt64", testKeyedContainerEncodesInt64),
        ("testKeyedContainerEncodesInt8", testKeyedContainerEncodesInt8),
        ("testKeyedContainerEncodesInt", testKeyedContainerEncodesInt),
        ("testKeyedContainerEncodesNestedKeyed", testKeyedContainerEncodesNestedKeyed),
        ("testKeyedContainerEncodesNestedType", testKeyedContainerEncodesNestedType),
        ("testKeyedContainerEncodesNestedUnkeyed", testKeyedContainerEncodesNestedUnkeyed),
        ("testKeyedContainerEncodesNil", testKeyedContainerEncodesNil),
        ("testKeyedContainerEncodesString", testKeyedContainerEncodesString),
        ("testKeyedContainerEncodesUInt16", testKeyedContainerEncodesUInt16),
        ("testKeyedContainerEncodesUInt32", testKeyedContainerEncodesUInt32),
        ("testKeyedContainerEncodesUInt64", testKeyedContainerEncodesUInt64),
        ("testKeyedContainerEncodesUInt8", testKeyedContainerEncodesUInt8),
        ("testKeyedContainerEncodesUInt", testKeyedContainerEncodesUInt),
        ("testKeyedContainerSuperEncoder", testKeyedContainerSuperEncoder),
        ("testSimple", testSimple),
        ("testSingleContainerEncodesBool", testSingleContainerEncodesBool),
        ("testSingleContainerEncodesDouble", testSingleContainerEncodesDouble),
        ("testSingleContainerEncodesFloat", testSingleContainerEncodesFloat),
        ("testSingleContainerEncodesInt16", testSingleContainerEncodesInt16),
        ("testSingleContainerEncodesInt32", testSingleContainerEncodesInt32),
        ("testSingleContainerEncodesInt64", testSingleContainerEncodesInt64),
        ("testSingleContainerEncodesInt8", testSingleContainerEncodesInt8),
        ("testSingleContainerEncodesInt", testSingleContainerEncodesInt),
        ("testSingleContainerEncodesNil", testSingleContainerEncodesNil),
        ("testSingleContainerEncodesType", testSingleContainerEncodesType),
        ("testSingleContainerEncodesUInt16", testSingleContainerEncodesUInt16),
        ("testSingleContainerEncodesUInt32", testSingleContainerEncodesUInt32),
        ("testSingleContainerEncodesUInt64", testSingleContainerEncodesUInt64),
        ("testSingleContainerEncodesUInt8", testSingleContainerEncodesUInt8),
        ("testSingleContainerEncodesUInt", testSingleContainerEncodesUInt),
        ("testSingleContainerThrowsWhenEmpty", testSingleContainerThrowsWhenEmpty),
        ("testUnkeyedContainerAppendsKeypath", testUnkeyedContainerAppendsKeypath),
        ("testUnkeyedContainerCountIncrements", testUnkeyedContainerCountIncrements),
        ("testUnkeyedContainerEncodesBool", testUnkeyedContainerEncodesBool),
        ("testUnkeyedContainerEncodesDouble", testUnkeyedContainerEncodesDouble),
        ("testUnkeyedContainerEncodesFloat", testUnkeyedContainerEncodesFloat),
        ("testUnkeyedContainerEncodesInt16", testUnkeyedContainerEncodesInt16),
        ("testUnkeyedContainerEncodesInt32", testUnkeyedContainerEncodesInt32),
        ("testUnkeyedContainerEncodesInt64", testUnkeyedContainerEncodesInt64),
        ("testUnkeyedContainerEncodesInt8", testUnkeyedContainerEncodesInt8),
        ("testUnkeyedContainerEncodesInt", testUnkeyedContainerEncodesInt),
        ("testUnkeyedContainerEncodesNestedKeyed", testUnkeyedContainerEncodesNestedKeyed),
        ("testUnkeyedContainerEncodesNestedType", testUnkeyedContainerEncodesNestedType),
        ("testUnkeyedContainerEncodesNestedUnkeyed", testUnkeyedContainerEncodesNestedUnkeyed),
        ("testUnkeyedContainerEncodesNil", testUnkeyedContainerEncodesNil),
        ("testUnkeyedContainerEncodesString", testUnkeyedContainerEncodesString),
        ("testUnkeyedContainerEncodesUInt16", testUnkeyedContainerEncodesUInt16),
        ("testUnkeyedContainerEncodesUInt32", testUnkeyedContainerEncodesUInt32),
        ("testUnkeyedContainerEncodesUInt64", testUnkeyedContainerEncodesUInt64),
        ("testUnkeyedContainerEncodesUInt8", testUnkeyedContainerEncodesUInt8),
        ("testUnkeyedContainerEncodesUInt", testUnkeyedContainerEncodesUInt),
        ("testUnkeyedContainerSuperEncoder", testUnkeyedContainerSuperEncoder),
        ("testVoidEncodeMethodThrowsError", testVoidEncodeMethodThrowsError),
    ]
}

extension UserDefaultsCodableTests {
    static let __allTests = [
        ("testCanDecode", testCanDecode),
        ("testCanDecodeOptional", testCanDecodeOptional),
        ("testCanEncode", testCanEncode),
        ("testCanEncodeOptional", testCanEncodeOptional),
        ("testThrowsWhenInvalidDictionary", testThrowsWhenInvalidDictionary),
        ("testThrowsWhenKeyMissing", testThrowsWhenKeyMissing),
    ]
}

#if !os(macOS)
public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DictionaryDecoderTests.__allTests),
        testCase(DictionaryEncoderTests.__allTests),
        testCase(UserDefaultsCodableTests.__allTests),
    ]
}
#endif
